name: webviewtube
description: Play YouTube videos on mobile platforms, using WebView and IFrame Player API.
version: 3.0.0
repository: https://github.com/yh-luo/webviewtube

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.16.6"

platforms:
  android:
  ios:

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.4
  webview_flutter: ^4.11.0
  webview_flutter_android: ^4.4.1
  webview_flutter_wkwebview: ^3.20.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.6
  webview_flutter_platform_interface: ^2.11.0
